# Generated by Django 4.1 on 2022-11-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
