# Generated by Django 4.1 on 2022-11-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_task_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation',
            field=models.DateTimeField(),
        ),
    ]
